import dotenv from 'dotenv'
// Prefer .env.local (Next.js convention) then fall back to .env
dotenv.config({ path: '.env.local' })
dotenv.config()

// Ensure DATABASE_URL is a string (some loaders may provide non-string values)
if (process.env.DATABASE_URL !== undefined) {
  process.env.DATABASE_URL = String(process.env.DATABASE_URL)
}

// Debug info: type and basic checks (password masked)
const raw = process.env.DATABASE_URL
console.log('DATABASE_URL type:', typeof raw)
if (raw) {
  const masked = raw.replace(/:(.*)@/, ':<redacted>@')
  console.log('DATABASE_URL sample:', masked)
  console.log('contains postgresql://', raw.startsWith('postgresql://'))
  console.log('length:', raw.length)
} else {
  console.log('DATABASE_URL is not set')
}

import { sql } from 'drizzle-orm'
import { employees, roster_anchors, movement_requests } from './schema.ts'
import { Pool } from 'pg'
import { drizzle } from 'drizzle-orm/node-postgres/index.js'

// Create our own pool from DATABASE_URL to avoid connectionString parsing issues
const parsed = new URL(process.env.DATABASE_URL || '')
const pool = new Pool({ host: parsed.hostname, port: Number(parsed.port), user: parsed.username, password: parsed.password, database: parsed.pathname.replace('/', '') })
const db = drizzle(pool)

// Extra debugging: parse the DATABASE_URL and log username/password types
try {
  const u = new URL(process.env.DATABASE_URL || '')
  console.log('URL username type:', typeof u.username, 'value:', u.username)
  console.log('URL password type:', typeof u.password, 'value length:', u.password.length)
  // Try connecting with pg directly using explicit fields
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { Pool } = await import('pg')
  const pool = new Pool({ host: u.hostname, port: Number(u.port), user: u.username, password: u.password, database: u.pathname.replace('/', '') })
  try {
    const client = await pool.connect()
    await client.query('SELECT 1')
    client.release()
    await pool.end()
    console.log('Direct PG connection succeeded')
  } catch (err) {
    console.error('Direct PG connect error:', err.message)
    await pool.end()
  }
} catch (err) {
  console.error('URL parse/connect debug failed:', err.message)
}

async function main() {
  // Clear child tables first
  await db.delete(movement_requests).where(sql`1=1`)
  await db.delete(roster_anchors).where(sql`1=1`)
  await db.delete(employees).where(sql`1=1`)

  const mockEmployees = [
    { name: 'Alice Ramos', department: 'Operations', role: 'Operator' },
    { name: 'Ben Carter', department: 'Operations', role: 'Supervisor' },
    { name: 'Clara Ng', department: 'Operations', role: 'Manager' },
    { name: 'Diego Silva', department: 'Logistics', role: 'Logistics Coordinator' },
    { name: 'Eva Ma', department: 'Logistics', role: 'Driver' },
    { name: 'Frank Ortiz', department: 'Logistics', role: 'Loader' },
    { name: 'Gina Park', department: 'Engineering', role: 'Maintenance Engineer' },
    { name: 'Hiro Tanaka', department: 'Engineering', role: 'Technician' },
    { name: 'Ivy Singh', department: 'Engineering', role: 'Technician' },
    { name: 'James Lee', department: 'Operations', role: 'Operator' },
    { name: 'Khalid Noor', department: 'Logistics', role: 'Driver' },
    { name: 'Lena Ortiz', department: 'Engineering', role: 'Maintenance Engineer' },
    { name: 'Marta Cruz', department: 'Operations', role: 'Supervisor' },
    { name: 'Nico Rossi', department: 'Logistics', role: 'Coordinator' },
    { name: 'Olga Petrova', department: 'Engineering', role: 'Technician' },
  ]

  const inserted = await db.insert(employees).values(mockEmployees).returning()

  const base = new Date('2023-01-01')
  const anchors = inserted.map((e, idx) => {
    const offsetDays = (idx % 3) * 7 // 0,7,14
    const d = new Date(base)
    d.setDate(d.getDate() + offsetDays)
    return { employee_id: e.id as number, anchor_date: d.toISOString().slice(0, 10) }
  })

  await db.insert(roster_anchors).values(anchors)

  // Create 7 pending movement requests across departments
  const pick = (arr: any[], n: number) => {
    const out: any[] = []
    const copy = [...arr]
    while (out.length < n && copy.length) {
      const i = Math.floor(Math.random() * copy.length)
      out.push(copy.splice(i, 1)[0])
    }
    return out
  }

  const chosen = pick(inserted, 7)
  const requests = chosen.map((e, i) => ({
    employee_id: e.id as number,
    movement_type: i % 2 === 0 ? 'Change Swing' : 'Leave Request',
    start_date: new Date(Date.now() + i * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    end_date: new Date(Date.now() + (i + 3) * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
    status: 'Pending',
    current_comment: 'Generated by seed script',
  }))

  await db.insert(movement_requests).values(requests)

  console.log('Seeding complete')
}

main()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err)
    process.exit(1)
  })
